language: node_js
node_js:
  - 6.1
env:
  global:
    - NPM_ORG=@grabrinc
    - GIT_NAME=Travis-CI
    - GIT_EMAIL=travis-ci@grabr.io
before_install:
  - npm i -g makeshift
  - makeshift -s $NPM_ORG -r registry.npmjs.org
  - git config --global user.name $GIT_NAME
  - git config --global user.email $GIT_EMAIL
install:
  - npm i
  - npm version patch -m "%s [ci skip]"
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = push

  # Token is defined in Travis CI settings.
  api_key: $NPM_TOKEN
  script: >
    set -ex;
    git push origin HEAD:$TRAVIS_BRANCH;
    npm publish;